name: Flask Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Deploy application to PythonAnywhere
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        echo "Deploying to PythonAnywhere..."
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ env.PA_USERNAME }}/files/path/home/${{ env.PA_USERNAME }}/your_project/ \
          -H "Authorization: Token ${{ env.PA_API_TOKEN }}" \
          --form "path=app.py" \
          --form "content=@app.py"
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ env.PA_USERNAME }}/webapps/ \
          -H "Authorization: Token ${{ env.PA_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "path": "/home/${{ env.PA_USERNAME }}/your_project",
                "virtualenv_path": "/home/${{ env.PA_USERNAME }}/your_project/venv",
                "source_directory": "/home/${{ env.PA_USERNAME }}/your_project",
                "web_framework": "flask"
              }'

    - name: Test prediction endpoint
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
      run: |
        echo "Testing the /predict endpoint..."
        curl -X POST -H "Content-Type: application/json" \
        -d '[{"km4week": 100, "sp4week": 12.5, "Category": "Male"}, {"km4week": 120, "sp4week": 14.0, "Category": "Female"}]' \
        https://${{ secrets.PA_USERNAME }}.pythonanywhere.com/predict
