name: Flask Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Add SSH key
      if: ${{ env.SERVER_IP != '127.0.0.1' }}
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy application (Local or Remote)
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        if [ "${{ env.SERVER_IP }}" = "127.0.0.1" ]; then
          echo "Running locally for testing..."
          gunicorn -w 4 -b 0.0.0.0:5000 app:app &
          sleep 10  # Aumenta el tiempo de espera
        else
          echo "Deploying to remote server..."
          ssh -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
            cd ${{ env.DEPLOY_PATH }}
            git pull origin main
            pip install -r requirements.txt
            pkill gunicorn || true
            gunicorn -w 4 -b 0.0.0.0:5000 app:app &
        EOF
          sleep 10
        fi

    - name: Test prediction endpoint
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "Testing the /predict endpoint..."
        curl -X POST -H "Content-Type: application/json" \
        -d '[{"km4week": 100, "sp4week": 12.5, "Category": "Male"}, {"km4week": 120, "sp4week": 14.0, "Category": "Female"}]' \
        http://${{ secrets.SERVER_IP }}:5000/predict
