name: Flask Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Deploy Locally
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        echo "Deploying to local environment..."
        cd ${{ env.DEPLOY_PATH }}
        python app.py &
        sleep 5
        curl -X GET http://${{ secrets.SERVER_IP }}:5000/predict
