name: Flask Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        echo "Deploying to local environment..."
        cd ${{ env.DEPLOY_PATH }}
        gunicorn -w 4 -b 0.0.0.0:5000 app:app &
        sleep 5

    - name: Test endpoint
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        curl -X GET http://${{ env.SERVER_IP }}:5000/predict
