name: Flask Deployment Pipeline

on:
  push:
    branches:
      - main  # Ejecutar el pipeline en cada cambio a la rama `main`

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask server and test endpoints
      run: |
        python app.py &
        sleep 5
        curl -X GET http://127.0.0.1:5000/predict
